# Generated by Django 2.1.4 on 2019-01-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profession', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=550)),
                ('email', models.CharField(max_length=250)),
                ('linkedin_url', models.CharField(max_length=250)),
                ('twitter', models.CharField(max_length=300)),
            ],
        ),
    ]
